name: ci-golang-workflow
on: 
  pull_request:  #it happens on pull request
    branches:
      - develop

jobs:
  check-applications:
    runs-on: ubuntu-latest #it happens on ubuntu-latest
    strategy:
      matrix: 
        go: ['1.14','1.15']
    steps:
      - uses: actions/checkout@v2 #common use, it download files
      - uses: actions/setup-go@v2 #common use, run go
        with:
          go-version: ${{ matrix.go }}
      - run: go test #execute commands
      - run: go run math.go
