name: ci-golang-workflow
on: [push]  #it happens on push
jobs:
  check-applications:
    runs-on: ubuntu-latest #it happens on ubuntu-latest
    steps:
      - uses: actions/checkout@v2 #common use, it download files
      - uses: actions/setup-go@v2 #common use, run go
        with:
          go-version: 1.15
      - run: go test #execute commands
      - run: go run math.go
