name: ci-golang-workflow
on: 
  pull_request:  #it happens on pull request
    branches:
      - develop

jobs:
  check-applications:
    runs-on: ubuntu-latest #it happens on ubuntu-latest
    steps:
      - uses: actions/checkout@v2 #common use, it download files
      - uses: actions/setup-go@v2 #common use, run go
        with:
          go-version: 1.15
      - run: go test #execute commands
      - run: go run math.go

      #run docker 
      - name: Checkout
        uses: actions/checkout@v3
      #setup docker to work some architectures
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      #build 
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        id: docker_build #using ID is possible use build results
        uses: docker/build-push-actions@v2
        with:
          push: false
          tags: poncion/edu-fc-ci-org:latest #build saved on instance